export const defaultAdvancedOptions = {
  appendPunctuations: '\'.。,，!！?？:：")]}、',
  beamSize: 5,
  bestOf: 5,
  clipTimestamps: 0,
  compressionRatioThreshold: 2.4,
  conditionOnPreviousText: true,
  device: 'cuda',
  fp16: true,
  hallucinationSilenceThreshold: 0,
  highlightWords: false,
  initialPrompt: '',
  language: 'English',
  lengthPenalty: 0,
  logprobThreshold: -1.0,
  maxLineCount: 0,
  maxLineWidth: 0,
  maxWordsPerLine: 0,
  model: 'turbo',
  noSpeechThreshold: 0.6,
  outputFormat: 'txt',
  patience: 1,
  prependPunctuations: '\'"¿([{-',
  suppressTokens: '-1',
  task: 'transcribe',
  temperature: 0,
  temperatureIncrementOnFallback: 0.2,
  threads: 0,
  verbose: true,
  wordTimestamps: false
};

export const deviceOptions = [
  { value: 'cpu', label: 'CPU' },
  { value: 'cuda', label: 'CUDA (GPU)' }
];

export const languageOptions = [
  'None',
  'Arabic',
  'Chinese',
  'English',
  'French',
  'German',
  'Italian',
  'Japanese',
  'Korean',
  'Mandarin',
  'Spanish',
  'Afrikaans',
  'Albanian',
  'Amharic',
  'Armenian',
  'Assamese',
  'Azerbaijani',
  'Bashkir',
  'Basque',
  'Belarusian',
  'Bengali',
  'Bosnian',
  'Breton',
  'Bulgarian',
  'Burmese',
  'Cantonese',
  'Castilian',
  'Catalan',
  'Croatian',
  'Czech',
  'Danish',
  'Dutch',
  'Estonian',
  'Faroese',
  'Finnish',
  'Flemish',
  'Galician',
  'Georgian',
  'Greek',
  'Gujarati',
  'Haitian',
  'Haitian Creole',
  'Hausa',
  'Hawaiian',
  'Hebrew',
  'Hindi',
  'Hungarian',
  'Icelandic',
  'Indonesian',
  'Javanese',
  'Kannada',
  'Kazakh',
  'Khmer',
  'Lao',
  'Latin',
  'Latvian',
  'Letzeburgesch',
  'Lingala',
  'Lithuanian',
  'Luxembourgish',
  'Macedonian',
  'Malagasy',
  'Malay',
  'Malayalam',
  'Maltese',
  'Maori',
  'Marathi',
  'Moldavian',
  'Moldovan',
  'Mongolian',
  'Myanmar',
  'Nepali',
  'Norwegian',
  'Nynorsk',
  'Occitan',
  'Panjabi',
  'Pashto',
  'Persian',
  'Polish',
  'Portuguese',
  'Punjabi',
  'Pushto',
  'Romanian',
  'Russian',
  'Sanskrit',
  'Serbian',
  'Shona',
  'Sindhi',
  'Sinhala',
  'Sinhalese',
  'Slovak',
  'Slovenian',
  'Somali',
  'Sundanese',
  'Swahili',
  'Swedish',
  'Tagalog',
  'Tajik',
  'Tamil',
  'Tatar',
  'Telugu',
  'Thai',
  'Tibetan',
  'Turkish',
  'Turkmen',
  'Ukrainian',
  'Urdu',
  'Uzbek',
  'Valencian',
  'Vietnamese',
  'Welsh',
  'Yiddish',
  'Yoruba'
];

export const modelOptions = [
  { value: 'tiny', label: 'Tiny' },
  { value: 'base', label: 'Base' },
  { value: 'small', label: 'Small' },
  { value: 'medium', label: 'Medium' },
  { value: 'large', label: 'Large' },
  { value: 'turbo', label: 'Turbo' }
];

export const outputFormatOptions = [
  { value: 'all', label: 'All' },
  { value: 'json', label: 'JSON' },
  { value: 'srt', label: 'SubRip' },
  { value: 'tsv', label: 'Tab-Separated Values' },
  { value: 'txt', label: 'Text' },
  { value: 'vtt', label: 'WebVTT' }
];

export const taskOptions = [
  { value: 'transcribe', label: 'Transcribe' },
  { value: 'translate', label: 'Translate' }
];
